services:
  - type: web
    name: freudmusic-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simple_main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: PORT
        value: 10000 